export const feeds = [
    // Western
    { url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', group: 'western', language: 'en' },
    { url: 'https://feeds.bbci.co.uk/news/rss.xml', group: 'western', language: 'en' },
    { url: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml', group: 'western', language: 'en' },
    { url: 'https://www.npr.org/rss/rss.php?id=1001', group: 'western', language: 'en' },
    { url: 'https://rss.cnn.com/rss/edition.rss', group: 'western', language: 'en' },
    { url: 'https://feeds.foxnews.com/foxnews/latest', group: 'western', language: 'en' },
    { url: 'https://www.theguardian.com/uk/rss', group: 'western', language: 'en' },
    { url: 'https://www.independent.co.uk/news/uk/rss', group: 'western', language: 'en' },
    // Nonwestern
    { url: 'http://www.xinhuanet.com/english/rss/worldrss.xml', group: 'nonwestern', language: 'en' },
    { url: 'https://ria.ru/export/rss2/world/index.xml', group: 'nonwestern', language: 'ru' },
    { url: 'https://tass.com/rss/v2.xml', group: 'nonwestern', language: 'ru' },
    { url: 'https://www.globaltimes.cn/rss/world.xml', group: 'nonwestern', language: 'en' },
    { url: 'https://www3.nhk.or.jp/rss/news/cat0.xml', group: 'nonwestern', language: 'ja' },
    { url: 'https://www.japantimes.co.jp/feed/', group: 'nonwestern', language: 'en' },
    { url: 'https://g1.globo.com/dynamo/rss2.xml', group: 'nonwestern', language: 'pt' },
    { url: 'https://www1.folha.uol.com.br/rss/folha_mundo.xml', group: 'nonwestern', language: 'pt' },
    { url: 'https://www.youm7.com/rss/SectionRss?SectionID=97', group: 'nonwestern', language: 'ar' },
    { url: 'https://english.ahram.org.eg/Portal/1/News/rss.aspx', group: 'nonwestern', language: 'en' },
    { url: 'https://www.hurriyet.com.tr/rss/anasayfa', group: 'nonwestern', language: 'tr' },
    { url: 'https://www.dailysabah.com/rss', group: 'nonwestern', language: 'en' },
    { url: 'https://www.korea.net/rss/news.xml', group: 'nonwestern', language: 'en' },
    { url: 'https://www.koreatimes.co.kr/www/rss/rss.xml', group: 'nonwestern', language: 'en' },
    { url: 'https://www.eluniversal.com.mx/rss/ciencia.xml', group: 'nonwestern', language: 'es' },
    { url: 'https://www.milenio.com/rss/ultima-hora', group: 'nonwestern', language: 'es' },
    { url: 'https://www.vanguardngr.com/feed/', group: 'nonwestern', language: 'en' },
    { url: 'https://www.premiumtimesng.com/feed', group: 'nonwestern', language: 'en' },
    { url: 'https://www.antaranews.com/rss/nasional', group: 'nonwestern', language: 'id' },
    { url: 'https://www.thejakartapost.com/rss', group: 'nonwestern', language: 'en' },
    { url: 'https://www.spa.gov.sa/rss/1.xml', group: 'nonwestern', language: 'ar' },
    { url: 'https://english.alarabiya.net/.mrss/en/news.xml', group: 'nonwestern', language: 'en' },
    { url: 'https://www.irna.ir/rss/tp/20', group: 'nonwestern', language: 'fa' },
    { url: 'https://en.mehrnews.com/rss', group: 'nonwestern', language: 'en' },
    { url: 'https://www.dawn.com/feeds/home', group: 'nonwestern', language: 'en' },
    { url: 'https://tribune.com.pk/feed/', group: 'nonwestern', language: 'en' },
    { url: 'https://www.bangkokpost.com/rss/data/topstories.xml', group: 'nonwestern', language: 'en' },
    { url: 'https://www.nationthailand.com/rss/national', group: 'nonwestern', language: 'en' },
]; 